### ISSUE TITLE
1

### ISSUE THREAD

**Issue by kusochek** [DenysTymchenko/Code-Quizzer#1]
https://github.com/DenysTymchenko/Quiz-App/blob/520b8a1d1dc3d03bb73cbdc6e7e420ce9ca585ed/src/components/QuizCard/QuizCard.jsx#L44
https://github.com/DenysTymchenko/Quiz-App/blob/520b8a1d1dc3d03bb73cbdc6e7e420ce9ca585ed/src/components/QuizCard/QuizCard.jsx#L58
https://github.com/DenysTymchenko/Quiz-App/blob/520b8a1d1dc3d03bb73cbdc6e7e420ce9ca585ed/src/components/QuizCard/QuizCard.jsx#L74

delete unnecessary new line it's for example delete it in other components too

**Comment by DenysTymchenko** [comment]
done: https://github.com/DenysTymchenko/Quiz-App/commit/2b58c8246c56493353b2f63e345146cdcb982ed4
