### ISSUE TITLE
2

### ISSUE THREAD

**Issue by kusochek** [DenysTymchenko/Code-Quizzer#2]
https://github.com/DenysTymchenko/Quiz-App/blob/520b8a1d1dc3d03bb73cbdc6e7e420ce9ca585ed/src/components/QuizCard/QuizCard.jsx#L85

after {isStarted &&
new line will be look better

**Comment by DenysTymchenko** [comment]
done: https://github.com/DenysTymchenko/Quiz-App/commit/efacf685847cfc83d5998b2fef4a5ab9c0caa0f8
